# Generated by Django 4.0.6 on 2022-07-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion', verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion', verbose_name='modificado')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
            ],
            options={
                'abstract': False,
            },
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
            ],
            options={
                'abstract': False,
            },
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
            ],
            options={
                'abstract': False,
            },
            bases=('item.item',),
        ),
    ]
