name: Actualizar contenedor

on:
  push:
    banches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout
    
    - name: Iniciar contenedor Docker
      run: |
        sudo docker-compose down
        sudo docker-compose build
        sudo docker-compose up -d
